# Generated by Django 3.2.16 on 2022-12-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='email',
            field=models.EmailField(default=112222, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='phone_num',
            field=models.IntegerField(default=1122),
            preserve_default=False,
        ),
    ]
